// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhTjTdTHa5xyZPpM_khIHxxTBTbBK6RNQ',
    appId: '1:937469130987:web:a7a81fb2f6c341951d26ae',
    messagingSenderId: '937469130987',
    projectId: 'golpo-4e336',
    authDomain: 'golpo-4e336.firebaseapp.com',
    storageBucket: 'golpo-4e336.firebasestorage.app',
    measurementId: 'G-S370BRK2G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeKESofcFdUdL6AoktyQyxlFh6_jkWstM',
    appId: '1:937469130987:android:dc1a8460c30b77fe1d26ae',
    messagingSenderId: '937469130987',
    projectId: 'golpo-4e336',
    storageBucket: 'golpo-4e336.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArVn7UlBkaw07WWhvpME8SiCS__4Kx5mM',
    appId: '1:937469130987:ios:392421fd7f678b961d26ae',
    messagingSenderId: '937469130987',
    projectId: 'golpo-4e336',
    storageBucket: 'golpo-4e336.firebasestorage.app',
    iosClientId: '937469130987-jsvmjpg4lathn496sjj98e17t2p25f8f.apps.googleusercontent.com',
    iosBundleId: 'com.golpo.golpo',
  );
}
